apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.204.61.65/32
        - 10.204.61.67/32
